// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzmokyheiizcfxbmtsqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6bW9reWhlaWl6Y2Z4Ym10c3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDczMTYsImV4cCI6MjA2MTkyMzMxNn0.a74_MbHscbyOeZns_vgI_8YUkDuPjT5Y4JF3HxBc__A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);